# based image yang akan digunakan
FROM node:lts-hydrogen

# untuk set ENV dalam aplikasi kita
ENV PORT=4000
ENV NODE_ENV=production
ENV BASE_PORT_REDIS=15264
ENV BASE_URL_REDIS="redis://default:TROHtwyTBTSdqHFN8QczJt38QN9jbUcs@redis-15264.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:15264"

# path di container dimana berisi codingan kita (path bebas sesuai kesepakatan bersama)
WORKDIR /app

# copy deps yang ada di apps ke WORKDIR
COPY ["package.json", "package-lock.json*", "./"]

# Install npm & Mengapus cache
RUN npm install --production && npm cache clean --force

# copy semua file & folder ke WORKDIR
COPY . .

# execute apps: production
CMD ["npm", "start"]